### ISSUE TITLE
CMAKE_OSX_ARCHITECTURES for both ARM and Intel

### ISSUE THREAD

**Issue by ilya-lavrenov** [cansik/openvino-arm#1]
Hi,

Have you tried to use `CMAKE_OSX_ARCHITECTURES` set to both Intel and ARM? Will universal python binaries build in this case?
E.g. I can use such binaries on both Intel and ARM platforms running OSX 11 or 12.

What would be the arch in the wheel package name in this case?

**Comment by cansik** [comment]
@ilya-lavrenov I have done that in the [pyrealsense2 library](https://github.com/cansik/pyrealsense2-macosx) for M1 (and Intel). The package name then looks like this: `macosx_11_0_universal2`. My expectation was that it would not make any sense for openvino because of the current limitations of the arm package. Or would it use the normal backend on intel and the contrib on arm?

**Comment by cansik** [comment]
@ilya-lavrenov I tried it out, does not work with the flag `-DCMAKE_OSX_ARCHITECTURES="arm64;x86_64"`.
Here the error message:

```
[ 45%] Built target arm_compute_static_libs
make[1]: *** [src/bindings/python/wheel/CMakeFiles/ie_wheel.dir/rule] Error 2
make: *** [ie_wheel] Error 2
```
